#!/usr/bin/env bash
set -eux

# 1) Download & install code-server
CODE_SERVER_VER="4.21.1"
wget -qO code-server.deb \
  https://github.com/coder/code-server/releases/download/v${CODE_SERVER_VER}/code-server_${CODE_SERVER_VER}_amd64.deb
sudo dpkg -i code-server.deb
rm code-server.deb

# 2) Ensure the JLab extension is up to date
pip install --no-deps --upgrade jupyterlab_vscode

# 3) Symlink for convenience
ln -sf /usr/bin/code-server /usr/local/bin/code-server
